# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['xmrig_client.py'],
    pathex=[],
    binaries=[],
    datas=[
    ('xmrig_gui.py', '.'),
    ('xmrig_client.py', '.'),
    ('xmrig_data.py', '.'),
    ('xmrig_miner.py', '.'),
    ('icons', 'icons'),
    ('tools', 'tools'),
    ('C:\\Users\\natem\\PycharmProjects\\moneroProject\\LibreHardwareMonitorLib.dll', '.'),
    ('C:\\Users\\natem\\PycharmProjects\\moneroProject\\HidSharp.dll', '.'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[   'PyQt5.QtBluetooth',
                 'PyQt5.QtDesigner',
                 'PyQt5.QtHelp',
                 'PyQt5.QtLocation',
                 'PyQt5.QtMultimedia',
                 'PyQt5.QtMultimediaWidgets',
                 'PyQt5.QtNetwork',
                 'PyQt5.QtNfc',
                 'PyQt5.QtOpenGL',
                 'PyQt5.QtPositioning',
                 'PyQt5.QtPrintSupport',
                 'PyQt5.QtQml',
                 'PyQt5.QtQuick',
                 'PyQt5.QtQuickWidgets',
                 'PyQt5.QtSensors',
                 'PyQt5.QtSerialPort',
                 'PyQt5.QtSql',
                 'PyQt5.QtSvg',
                 'PyQt5.QtTest',
                 'PyQt5.QtWebChannel',
                 'PyQt5.QtWebEngineCore',
                 'PyQt5.QtWebEngineWidgets',
                 'PyQt5.QtWebKit',
                 'PyQt5.QtWebKitWidgets',
                 'PyQt5.QtWebSockets',
                 'PyQt5.QtXml',
                 'PyQt5.QtXmlPatterns',],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    uac_admin=True,
    codesign_identity=None,
    entitlements_file=None,
)
